---
- name: build and link containers
  hosts: all
  become: yes

  tasks:
  - name: install python modules
    pip:
      name: "{{item}}"
      state: present
    with_items:
      - docker-py==1.10.6
      - docker-compose==1.9.0

  - name: build mysql image
    docker_image:
      path: ./mysql
      name: mysqlimage
      tag: sqltag



  - name: build php image
    docker_image:
      path: ./php
      name: phpimage
      tag: phptag


  - name: create mysql container
    docker_container:
      name: mysqlcontainer
      image: mysqlimage:sqltag
      networks:
        - name: bridge

  - name: sleep
    shell: "sleep 15"

  - name: sql command
    shell: "docker exec -i mysqlcontainer mysql -uroot -ppass4root < mysql/createuser.sql"

  - name: sql command
    shell: "docker exec -i mysqlcontainer mysql -ucsci459 -pcsci459 < mysql/createdata.sql"

  - name: sql command
    shell: 'docker exec -i mysqlcontainer mysql -ucsci459 -pcsci459 -e "select * from testdb.testtab;"'


  - name: create php container and link to mysqlContainer
    docker_container:
      name: phpcontainer
      image: phpimage:phptag
      networks:
        - name: bridge
          links:
            - mysqlcontainer
      ports:
        - "8080:80"
